version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    environment:
      - MONGODB_ROOT_USER=adminuser
      - MONGODB_ROOT_PASSWORD=rootpassword123
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local